// Build base graph from TSVs generated by database/build_bulk.py.

// 1) Items
LOAD CSV WITH HEADERS FROM 'file:///items.csv' AS row
FIELDTERMINATOR '\t'
CALL {
  WITH row
  MERGE (:Item {item_id: toInteger(row.item_id)})
} IN TRANSACTIONS OF 10000 ROWS;

// 2) Sessions
LOAD CSV WITH HEADERS FROM 'file:///sessions.csv' AS row
FIELDTERMINATOR '\t'
CALL {
  WITH row
  MERGE (:Session {session_id: toInteger(row.session_id)})
} IN TRANSACTIONS OF 10000 ROWS;

// 3) CONTAINS
LOAD CSV WITH HEADERS FROM 'file:///contains_typed.csv' AS row
FIELDTERMINATOR '\t'
CALL {
  WITH row
  MATCH (s:Session {session_id: toInteger(row.session_id)})
  MATCH (i:Item {item_id: toInteger(row.item_id)})
  MERGE (s)-[:CONTAINS]->(i)
} IN TRANSACTIONS OF 10000 ROWS;

// 4) NEXT
LOAD CSV WITH HEADERS FROM 'file:///next_typed.csv' AS row
FIELDTERMINATOR '\t'
CALL {
  WITH row
  MATCH (src:Item {item_id: toInteger(row.src_item_id)})
  MATCH (dst:Item {item_id: toInteger(row.dst_item_id)})
  MERGE (src)-[r:NEXT]->(dst)
  SET r.weight = toInteger(row.weight),
      r.updated_at = timestamp()
} IN TRANSACTIONS OF 10000 ROWS;
